##
# library build
##

image: Previous Visual Studio 2022

version: 8.0.{build}

configuration:
- Debug

platform: Any CPU

pull_requests:  
  do_not_increment_build_number: true

skip_commits:
  files:
    - CHANGELOG.md
    - appveyor.yml
    - repository.json
    - src/version.json

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  JAVA_HOME: C:\Program Files\Java\jdk19
  SONAR_TOKEN:
    secure: fNmV/P8zSNwd3LWpzw2nnm807oe1Hr0gr11hTItGCXmnVQ0tHN1ESPUjLYjsXmpG
  RESTRICTED_WORDS:
    secure: y2oCk9wYmgBAzk4m1tsSFUOlcEePEjozzMCfC0p6NQI=

install:
- ps: ./dotenv.ps1
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
- ps: Get-ChildItem "Env:"

before_build:
- appveyor-retry dotnet restore src -v Minimal
- set DNX_BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%
- dotnet --info
- ps: ./prebuild.ps1

build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true 
  include_nuget_references: true
  verbosity: minimal

build_script:
- pwsh: .\appveyor-build.ps1

artifacts:
- path: artifacts\**\*.*

cache:
- '%USERPROFILE%\.nuget\packages'
  
nuget:
  disable_publish_on_pr: true
  
deploy:
- provider: NuGet
  api_key:
    secure: D7B7/pzGIeteV3H4DrdBtyKCxLrgcBAL6XWtWrm/kJrshDwUZ5acauR9QWll7TWi
